Repository issuebombom/team_project_vanilla_js, pull requests merged in 2023-06, with the labels that each got.

#7 feat: #1
  index.html
  main.js
  style.css
Labels: enhancement

#8 인증 키값 변경 main.js
  main.js
Labels: fix

#14 feat: #9 css fixed page style
  main.js
  style.css
Labels: style

#16 feat: #15 add regexp in searchBar
  main.js
Labels: enhancement

#20 chore: css dummy delete
  style.css
Labels: style

#21 docs: description 작성
  description.txt
Labels: documentation

#22 feat: #17, #18, #19 validation check
  main.js
Labels: enhancement

#23 style: modal background blur
  static/css/style.css
  static/js/modal.js
Labels: style
